
ALTER TABLE records
ADD COLUMN IF NOT EXISTS upper_unit INTEGER,
ADD COLUMN IF NOT EXISTS lower_unit INTEGER,
ADD COLUMN IF NOT EXISTS upper_cost INTEGER,
ADD COLUMN IF NOT EXISTS lower_cost INTEGER;
